"""
train_v2.py — RAPTOR 6D Pose Estimation Training Pipeline
=======================================================
Usage
-----
    python train_v2.py                        # uses config.yaml in the same directory
    python train_v2.py --config my_cfg.yaml   # use a custom config file

All hyperparameters live in config.yaml. Do NOT edit this file for routine
experimentation — edit the YAML instead.
"""

import argparse
import gc
import os
import signal
import sys
import time
import subprocess
from pathlib import Path
from typing import Any, Literal, TypeAlias, cast

import cv2
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as models
import yaml
from torch.amp.autocast_mode import autocast
from torch.amp.grad_scaler import GradScaler
from torch.utils.data import DataLoader, Dataset, random_split
from torch.utils.tensorboard.writer import SummaryWriter
from tqdm import tqdm

# =============================================================================
# CONFIG LOADER
# =============================================================================

EpochScheduler: TypeAlias = (
    torch.optim.lr_scheduler.LambdaLR
    | torch.optim.lr_scheduler.StepLR
)
SchedulerType: TypeAlias = (
    EpochScheduler
    | torch.optim.lr_scheduler.ReduceLROnPlateau
    | None
)
SchedulerMode: TypeAlias = Literal["epoch", "plateau", "none"]

def load_config(path: str) -> dict[str, Any]:
    with open(path, "r") as f:
        cfg = yaml.safe_load(f)
    print(f"[Config] Loaded: {path}")
    return cfg


def cfg_get(cfg: dict[str, Any], *keys, default=None) -> Any:
    """Safe nested key access: cfg_get(cfg, 'training', 'lr')"""
    obj = cfg
    for k in keys:
        if not isinstance(obj, dict) or k not in obj:
            return default
        obj = obj[k]
    return obj


# =============================================================================
# GRACEFUL SHUTDOWN
# =============================================================================

_interrupted = False

def _handle_sigint(sig, frame):
    global _interrupted
    print("\n[INFO] Interrupt received — will checkpoint at end of this epoch.")
    _interrupted = True

signal.signal(signal.SIGINT, _handle_sigint)


# =============================================================================
# GPU LOGGER
# =============================================================================

def get_gpu_stats():
    try:
        result = subprocess.check_output(
            ["nvidia-smi",
             "--query-gpu=memory.used,memory.total,power.draw",
             "--format=csv,noheader,nounits"],
            timeout=5,
        )
        mem_used, mem_total, power = result.decode().strip().split(", ")
        return int(mem_used), int(mem_total), float(power)
    except Exception:
        return None, None, None


# =============================================================================
# AUGMENTATION
# =============================================================================

class PoseAugment:
    """
    Lightweight augmentation that preserves pose label validity.
    Geometric transforms (flip, rotation) that would change the ground-truth
    pose are intentionally excluded — only photometric and mild spatial
    distortions are applied.
    """

    def __init__(self, aug_cfg: dict, img_size: int):
        self.cfg      = aug_cfg
        self.img_size = img_size
        self.enabled  = aug_cfg.get("enabled", False)

    def __call__(self, img: np.ndarray) -> np.ndarray:
        """img: float32 H×W in [0,1]"""
        if not self.enabled:
            return img

        # Brightness jitter
        bj = self.cfg.get("brightness_jitter", 0.0)
        if bj > 0 and np.random.rand() < 0.5:
            delta = np.random.uniform(-bj, bj)
            img   = np.clip(img + delta, 0.0, 1.0)

        # Contrast jitter
        cj = self.cfg.get("contrast_jitter", 0.0)
        if cj > 0 and np.random.rand() < 0.5:
            factor = np.random.uniform(1.0 - cj, 1.0 + cj)
            mean   = img.mean()
            img    = np.clip((img - mean) * factor + mean, 0.0, 1.0)

        # Small rotation (does not invalidate 6-DoF label for modest angles)
        deg = self.cfg.get("rotation_degrees", 0)
        if deg > 0 and np.random.rand() < 0.5:
            angle = np.random.uniform(-deg, deg)
            h, w  = img.shape
            M     = cv2.getRotationMatrix2D((w / 2, h / 2), angle, 1.0)
            img   = cv2.warpAffine(img, M, (w, h),
                                   flags=cv2.INTER_LINEAR,
                                   borderMode=cv2.BORDER_REFLECT_101)

        # Gaussian blur
        gb = self.cfg.get("gaussian_blur", 0.0)
        if gb > 0 and np.random.rand() < gb:
            k   = np.random.choice([3, 5])
            img = cv2.GaussianBlur(img, (k, k), 0)

        return img


# =============================================================================
# DATASET
# =============================================================================

class SatellitePoseDataset(Dataset):

    def __init__(self, cfg: dict, train: bool = True):
        paths    = cfg["paths"]
        ds_cfg   = cfg["dataset"]
        aug_cfg  = ds_cfg.get("augmentation", {"enabled": False})

        df      = pd.read_csv(paths["csv_path"],  header=None)
        bbox_df = pd.read_csv(paths["bbox_path"], header=None)

        max_s = ds_cfg.get("max_samples")
        if max_s is not None:
            df      = df.iloc[:max_s]
            bbox_df = bbox_df.iloc[:max_s]

        # Convert to numpy once — eliminates per-sample pandas GIL overhead
        self.img_ids   = df.iloc[:, 0].to_numpy(dtype=np.int32)
        self.poses_raw = df.iloc[:, [1, 2, 3, 6, 7, 8, 9]].to_numpy(dtype=np.float32)
        self.bboxes    = bbox_df.iloc[:, [1, 2, 3, 4]].to_numpy(dtype=np.int32)

        self.img_dir  = paths["img_dir"]
        self.mask_dir = paths.get("mask_dir")
        self.img_size = int(ds_cfg.get("img_size", 224))
        self.train    = train
        self.augment  = PoseAugment(aug_cfg, self.img_size) if train else None
        # Match ImageNet normalization expected by pretrained backbones.
        self.imagenet_mean = np.array([0.485, 0.456, 0.406], dtype=np.float32)[:, None, None]
        self.imagenet_std = np.array([0.229, 0.224, 0.225], dtype=np.float32)[:, None, None]

        print(f"[Dataset] {'Train' if train else 'Val'} samples: {len(self.img_ids)}")

    def __len__(self):
        return len(self.img_ids)

    def __getitem__(self, idx):
        img_name = f"scene{self.img_ids[idx]}.png"
        img_path = os.path.join(self.img_dir, img_name)

        image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if image is None:
            print(f"[WARN] Missing: {img_path} — using black placeholder.")
            image = np.zeros((self.img_size, self.img_size), dtype=np.uint8)

        xmin, xmax, ymin, ymax = self.bboxes[idx]
        h, w = image.shape
        xmin = max(0, xmin)
        ymin = max(0, ymin)
        xmax = min(w, xmax)
        ymax = min(h, ymax)

        cropped = image[ymin:ymax, xmin:xmax]
        if cropped.size == 0:
            cropped = image

        # Optional segmentation mask
        if self.mask_dir:
            mask_path = os.path.join(self.mask_dir, img_name)
            if os.path.exists(mask_path):
                mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
                if mask is not None:
                    mask_crop = mask[ymin:ymax, xmin:xmax]
                    mask_bin  = (mask_crop > 0).astype(np.float32)
                    cropped   = (cropped.astype(np.float32) * mask_bin).astype(np.uint8)

        resized = cv2.resize(cropped, (self.img_size, self.img_size))
        img_f   = resized.astype(np.float32) / 255.0

        # Augmentation (train only)
        if self.augment is not None:
            img_f = self.augment(img_f)

        # Replicate grayscale to 3 channels, then apply ImageNet normalization.
        img_3 = np.stack([img_f, img_f, img_f], axis=0)
        img_3 = (img_3 - self.imagenet_mean) / self.imagenet_std
        image_tensor = torch.from_numpy(img_3)

        # Pose: tx,ty,tz / 100  +  quaternion normalised
        pose = self.poses_raw[idx].copy()
        pose[0:3] /= 100.0
        q_norm = np.linalg.norm(pose[3:])
        if q_norm > 1e-8:
            pose[3:] /= q_norm
        else:
            pose[3:] = np.array([0.0, 0.0, 0.0, 1.0], dtype=np.float32)

        return image_tensor, torch.from_numpy(pose)


# =============================================================================
# MODEL
# =============================================================================

def _make_backbone(name: str, pretrained: bool):
    """Returns (backbone_module, feature_dim)"""
    weights_map = {
        "resnet50":        models.ResNet50_Weights.IMAGENET1K_V1,
        "resnet101":       models.ResNet101_Weights.IMAGENET1K_V1,
        "efficientnet_b3": models.EfficientNet_B3_Weights.IMAGENET1K_V1,
        "efficientnet_b4": models.EfficientNet_B4_Weights.IMAGENET1K_V1,
    }
    if name not in weights_map:
        raise ValueError(f"Unknown backbone '{name}'. "
                         f"Choose from: {list(weights_map.keys())}")

    weights = weights_map[name] if pretrained else None

    if name.startswith("resnet"):
        try:
            resnet = getattr(models, name)(weights=weights)
        except Exception as err:
            print(f"[WARN] Could not load pretrained {name} weights ({err}); using random init.")
            resnet = getattr(models, name)(weights=None)
        feat_dim = resnet.fc.in_features
        backbone = nn.Sequential(*list(resnet.children())[:-1], nn.Flatten(1))
    else:   # EfficientNet
        try:
            effnet = getattr(models, name)(weights=weights)
        except Exception as err:
            print(f"[WARN] Could not load pretrained {name} weights ({err}); using random init.")
            effnet = getattr(models, name)(weights=None)
        feat_dim = effnet.classifier[1].in_features
        backbone = nn.Sequential(effnet.features, effnet.avgpool, nn.Flatten(1))

    return backbone, feat_dim


class PoseResNet(nn.Module):

    def __init__(self, model_cfg: dict):
        super().__init__()
        backbone_name = model_cfg.get("backbone",    "resnet50")
        pretrained    = model_cfg.get("pretrained",  True)
        head_hidden   = model_cfg.get("head_hidden", 512)
        dropout       = model_cfg.get("dropout",     0.3)

        self.backbone, feat_dim = _make_backbone(backbone_name, pretrained)

        self.head = nn.Sequential(
            nn.Linear(feat_dim, head_hidden),
            nn.BatchNorm1d(head_hidden),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),
            nn.Linear(head_hidden, 7),
        )

    def forward(self, x):
        return self.head(self.backbone(x))


# =============================================================================
# LOSS
# =============================================================================

class PoseLoss(nn.Module):

    def __init__(self, beta: float = 5.0, trans_loss_type: str = "smooth_l1"):
        super().__init__()
        self.beta = beta
        self.trans_loss_type = trans_loss_type

    def forward(self, pred, target):
        if self.trans_loss_type == "mse":
            trans_loss = torch.mean((pred[:, :3] - target[:, :3]) ** 2)
        else:
            trans_loss = F.smooth_l1_loss(pred[:, :3], target[:, :3], beta=0.01)

        pred_q   = pred[:, 3:]   / (torch.norm(pred[:, 3:],   dim=1, keepdim=True) + 1e-8)
        target_q = target[:, 3:] / (torch.norm(target[:, 3:], dim=1, keepdim=True) + 1e-8)

        dot      = torch.clamp(torch.abs(torch.sum(pred_q * target_q, dim=1)), 0.0, 1.0)
        rot_loss = torch.mean(1.0 - dot)

        return trans_loss + self.beta * rot_loss


# =============================================================================
# OPTIMISER FACTORY
# =============================================================================

def build_optimiser(name: str, params, opt_cfg: dict):
    lr  = float(opt_cfg.get("lr",           1e-4))
    wd  = float(opt_cfg.get("weight_decay", 1e-4))

    if name == "adamw":
        return torch.optim.AdamW(params, lr=lr, weight_decay=wd)
    elif name == "adam":
        return torch.optim.Adam(params, lr=lr, weight_decay=wd)
    elif name == "sgd":
        return torch.optim.SGD(
            params, lr=lr, weight_decay=wd,
            momentum=float(opt_cfg.get("momentum", 0.9)),
            nesterov=bool(opt_cfg.get("nesterov", True)),
        )
    else:
        raise ValueError(f"Unknown optimiser '{name}'")


# =============================================================================
# SCHEDULER FACTORY
# =============================================================================

def build_scheduler(
    name: str, optimizer, sched_cfg: dict, total_epochs: int
) -> tuple[SchedulerType, SchedulerMode]:
    if name == "cosine_warmup":
        warmup = int(sched_cfg.get("warmup_epochs", 3))
        min_lr = float(sched_cfg.get("min_lr",       1e-6))

        def lr_lambda(epoch):
            if epoch < warmup:
                return (epoch + 1) / warmup
            progress = (epoch - warmup) / max(1, total_epochs - warmup)
            return min_lr / optimizer.param_groups[0]["initial_lr"] + \
                   (1 - min_lr / optimizer.param_groups[0]["initial_lr"]) * \
                   0.5 * (1 + np.cos(np.pi * progress))

        # Store initial_lr so the lambda can reference it
        for pg in optimizer.param_groups:
            pg["initial_lr"] = pg["lr"]

        return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda), "epoch"

    elif name == "plateau":
        return torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer, mode="min",
            patience=int(sched_cfg.get("patience", 3)),
            factor=float(sched_cfg.get("factor",   0.5)),
        ), "plateau"

    elif name == "step":
        return torch.optim.lr_scheduler.StepLR(
            optimizer,
            step_size=int(sched_cfg.get("step_size", 10)),
            gamma=float(sched_cfg.get("gamma",       0.5)),
        ), "epoch"

    elif name == "none":
        return None, "none"

    else:
        raise ValueError(f"Unknown scheduler '{name}'")


# =============================================================================
# CHECKPOINT HELPERS
# =============================================================================

def save_checkpoint(path, epoch, model, optimizer, scheduler, scaler, best_val):
    ckpt_dir = os.path.dirname(path)
    if ckpt_dir:
        os.makedirs(ckpt_dir, exist_ok=True)
    model_to_save = model._orig_mod if hasattr(model, "_orig_mod") else model
    state = {
        "epoch":     epoch,
        "model":     model_to_save.state_dict(),
        "optimizer": optimizer.state_dict(),
        "scaler":    scaler.state_dict(),
        "best_val":  best_val,
    }
    if scheduler is not None:
        state["scheduler"] = scheduler.state_dict()

    tmp = path + ".tmp"
    torch.save(state, tmp)
    os.replace(tmp, path)   # atomic — crash-safe


def load_checkpoint(path, model, optimizer, scheduler, scaler, device):
    ckpt = torch.load(path, map_location=device, weights_only=True)
    model_to_load = model._orig_mod if hasattr(model, "_orig_mod") else model
    model_to_load.load_state_dict(ckpt["model"])
    optimizer.load_state_dict(ckpt["optimizer"])
    scaler.load_state_dict(ckpt["scaler"])
    if scheduler is not None and "scheduler" in ckpt:
        scheduler.load_state_dict(ckpt["scheduler"])
    return ckpt["epoch"] + 1, ckpt["best_val"]


# =============================================================================
# EARLY STOPPING
# =============================================================================

class EarlyStopping:

    def __init__(self, patience: int = 10, min_delta: float = 1e-5):
        self.patience  = patience
        self.min_delta = min_delta
        self.best      = float("inf")
        self.counter   = 0

    def step(self, val_loss: float) -> bool:
        """Returns True if training should stop."""
        if val_loss < self.best - self.min_delta:
            self.best    = val_loss
            self.counter = 0
        else:
            self.counter += 1
        return self.counter >= self.patience


# =============================================================================
# TRAIN / VAL LOOP
# =============================================================================

def run_epoch(model, loader, criterion, optimizer, scaler, device,
              train: bool, grad_clip: float, accum_steps: int,
              mixed_precision: bool, amp_dtype: torch.dtype,
              skip_nonfinite_batches: bool, oom_skip_batches: bool):

    model.train() if train else model.eval()
    total_loss = 0.0
    device_type = device.type
    processed_steps = 0
    pending_micro_steps = 0

    ctx = torch.enable_grad() if train else torch.no_grad()
    with ctx:
        loop = tqdm(loader, desc="  [Train]" if train else "  [Val  ]", leave=False)
        for step, (images, poses) in enumerate(loop, 1):
            images = images.to(device, non_blocking=True)
            poses  = poses.to(device,  non_blocking=True)

            try:
                amp_ctx = autocast(
                    device_type=device_type, dtype=amp_dtype, enabled=mixed_precision
                )
                with amp_ctx:
                    preds = model(images)
                    loss = criterion(preds, poses)
            except RuntimeError as err:
                if device.type == "cuda" and oom_skip_batches and "out of memory" in str(err).lower():
                    print("[WARN] CUDA OOM during batch; skipping batch and clearing cache.")
                    optimizer.zero_grad(set_to_none=True)
                    torch.cuda.empty_cache()
                    continue
                raise

            if skip_nonfinite_batches and not torch.isfinite(loss):
                print(f"[WARN] Non-finite loss ({loss.item()}) on step {step}; skipping batch.")
                optimizer.zero_grad(set_to_none=True)
                continue

            loss = loss / accum_steps

            if train:
                scaler.scale(loss).backward()
                pending_micro_steps += 1
                if pending_micro_steps >= accum_steps:
                    scaler.unscale_(optimizer)
                    torch.nn.utils.clip_grad_norm_(
                        model.parameters(), grad_clip, error_if_nonfinite=False
                    )
                    scaler.step(optimizer)
                    scaler.update()
                    optimizer.zero_grad(set_to_none=True)
                    pending_micro_steps = 0

            total_loss += loss.item() * accum_steps
            processed_steps += 1
            loop.set_postfix(loss=f"{loss.item() * accum_steps:.5f}")

    if train and pending_micro_steps > 0:
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(
            model.parameters(), grad_clip, error_if_nonfinite=False
        )
        scaler.step(optimizer)
        scaler.update()
        optimizer.zero_grad(set_to_none=True)

    return total_loss / max(1, processed_steps)


# =============================================================================
# MAIN
# =============================================================================

def main(config_path: str):
    cfg = load_config(config_path)
    required_paths = [
        str(cfg_get(cfg, "paths", "csv_path", default="")),
        str(cfg_get(cfg, "paths", "bbox_path", default="")),
        str(cfg_get(cfg, "paths", "img_dir", default="")),
    ]
    for required_path in required_paths:
        if not required_path or not os.path.exists(required_path):
            raise FileNotFoundError(f"Required path does not exist: {required_path}")

    # Seeds
    seed = int(cfg_get(cfg, "dataset", "seed", default=42))
    torch.manual_seed(seed)
    np.random.seed(seed)

    matmul_precision = str(cfg_get(cfg, "training", "matmul_precision", default="high"))
    allow_tf32 = bool(cfg_get(cfg, "training", "allow_tf32", default=True))
    cudnn_benchmark = bool(cfg_get(cfg, "training", "cudnn_benchmark", default=True))
    deterministic = bool(cfg_get(cfg, "training", "deterministic", default=False))
    if torch.cuda.is_available():
        torch.backends.cuda.matmul.allow_tf32 = allow_tf32
        torch.backends.cudnn.allow_tf32 = allow_tf32
        torch.backends.cudnn.benchmark = cudnn_benchmark and not deterministic
        torch.backends.cudnn.deterministic = deterministic
    if hasattr(torch, "set_float32_matmul_precision"):
        torch.set_float32_matmul_precision(matmul_precision)

    print("\n===== RAPTOR 6D Pose Training =====\n")

    # ── Datasets ──────────────────────────────────────────────────────────────
    full_train = SatellitePoseDataset(cfg, train=True)

    # We build one dataset and split; augmentation is applied based on the
    # train flag stored inside each subset wrapper below.
    combined = SatellitePoseDataset.__new__(SatellitePoseDataset)
    combined.__dict__.update(full_train.__dict__)  # share arrays

    val_split  = float(cfg_get(cfg, "dataset", "val_split", default=0.8))
    n_train    = int(val_split * len(combined))
    n_val      = len(combined) - n_train
    g          = torch.Generator().manual_seed(seed)

    train_ds, val_ds = random_split(combined, [n_train, n_val], generator=g)

    # Disable augmentation on val by patching the dataset's augment attr
    combined_val = SatellitePoseDataset.__new__(SatellitePoseDataset)
    combined_val.__dict__.update(full_train.__dict__)
    combined_val.augment = None
    val_ds = torch.utils.data.Subset(combined_val, val_ds.indices)

    dl_cfg    = cfg_get(cfg, "dataloader", default={})
    num_workers     = int(dl_cfg.get("num_workers",     6))
    prefetch_factor = int(dl_cfg.get("prefetch_factor", 4))
    pin_memory      = bool(dl_cfg.get("pin_memory",     True))
    batch_size      = int(cfg_get(cfg, "training", "batch_size", default=64))

    if num_workers > 0:
        train_loader = DataLoader(
            train_ds,
            batch_size=batch_size,
            shuffle=True,
            num_workers=num_workers,
            pin_memory=pin_memory,
            persistent_workers=True,
            prefetch_factor=prefetch_factor,
        )
        val_loader = DataLoader(
            val_ds,
            batch_size=batch_size,
            shuffle=False,
            num_workers=num_workers,
            pin_memory=pin_memory,
            persistent_workers=True,
            prefetch_factor=prefetch_factor,
        )
    else:
        train_loader = DataLoader(
            train_ds,
            batch_size=batch_size,
            shuffle=True,
            num_workers=0,
            pin_memory=pin_memory,
            persistent_workers=False,
        )
        val_loader = DataLoader(
            val_ds,
            batch_size=batch_size,
            shuffle=False,
            num_workers=0,
            pin_memory=pin_memory,
            persistent_workers=False,
        )

    print(f"[Loader] Train batches: {len(train_loader)}  "
          f"Val batches: {len(val_loader)}")

    # ── Device ────────────────────────────────────────────────────────────────
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[Device] {device}")

    # ── Model ─────────────────────────────────────────────────────────────────
    model: nn.Module = PoseResNet(cfg_get(cfg, "model", default={})).to(device)

    if cfg_get(cfg, "model", "compile", default=True) and hasattr(torch, "compile"):
        print("[Model] Compiling with torch.compile …")
        try:
            model = cast(nn.Module, torch.compile(model))
        except Exception as err:
            print(f"[WARN] torch.compile failed ({err}); continuing without compile.")

    total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"[Model] Trainable parameters: {total_params:,}")

    # ── Loss ─────────────────────────────────────────────────────────────────
    beta      = float(cfg_get(cfg, "loss", "beta", default=5.0))
    trans_loss_type = str(cfg_get(cfg, "loss", "trans_loss_type", default="smooth_l1"))
    criterion = PoseLoss(beta=beta, trans_loss_type=trans_loss_type)

    # ── Optimiser ─────────────────────────────────────────────────────────────
    opt_cfg   = cfg_get(cfg, "optimiser", default={})
    opt_name  = opt_cfg.get("name", "adamw")
    optimizer = build_optimiser(opt_name, model.parameters(), opt_cfg)

    # ── Scheduler ─────────────────────────────────────────────────────────────
    epochs     = int(cfg_get(cfg, "training", "epochs", default=50))
    sched_cfg  = cfg_get(cfg, "scheduler", default={})
    sched_name = sched_cfg.get("name", "cosine_warmup")
    scheduler, sched_mode = build_scheduler(sched_name, optimizer, sched_cfg, epochs)

    # ── AMP Scaler ────────────────────────────────────────────────────────────
    mixed_precision = bool(cfg_get(cfg, "training", "mixed_precision", default=True))
    amp_dtype = torch.float16 if device.type == "cuda" else torch.bfloat16
    use_amp = mixed_precision and (device.type in {"cuda", "cpu"})
    scaler = GradScaler(
        device=device.type,
        enabled=(use_amp and device.type == "cuda" and amp_dtype == torch.float16),
    )

    # ── TensorBoard ───────────────────────────────────────────────────────────
    log_dir = cfg_get(cfg, "paths", "log_dir", default="runs")
    writer  = SummaryWriter(log_dir=log_dir)
    print(f"[TensorBoard] Logs → {log_dir}   (run: tensorboard --logdir={log_dir})")

    # ── Resume ────────────────────────────────────────────────────────────────
    start_epoch   = 0
    best_val_loss = float("inf")
    ckpt_load     = cfg_get(cfg, "paths", "checkpoint_load")

    if ckpt_load and os.path.exists(ckpt_load):
        print(f"[Checkpoint] Resuming from {ckpt_load} …")
        start_epoch, best_val_loss = load_checkpoint(
            ckpt_load, model, optimizer, scheduler, scaler, device)
        print(f"[Checkpoint] Epoch {start_epoch}, best_val={best_val_loss:.6f}")

    # ── Early stopping ────────────────────────────────────────────────────────
    es_cfg     = cfg_get(cfg, "early_stopping", default={})
    es_enabled = bool(es_cfg.get("enabled", True))
    stopper    = EarlyStopping(
        patience  = int(es_cfg.get("patience",  10)),
        min_delta = float(es_cfg.get("min_delta", 1e-5)),
    ) if es_enabled else None

    # ── Training loop ─────────────────────────────────────────────────────────
    grad_clip   = float(cfg_get(cfg, "training", "grad_clip",   default=1.0))
    accum_steps = int(cfg_get(cfg,   "training", "accum_steps", default=1))
    skip_nonfinite_batches = bool(
        cfg_get(cfg, "training", "skip_nonfinite_batches", default=True)
    )
    oom_skip_batches = bool(cfg_get(cfg, "training", "oom_skip_batches", default=True))
    ckpt_save   = cfg_get(cfg, "paths", "checkpoint_save", default="last_checkpoint.pth")
    best_path   = cfg_get(cfg, "paths", "best_model_path", default="best_pose_model.pth")

    print(f"\n[Training] Starting — epochs {start_epoch+1} → {epochs}\n")

    for epoch in range(start_epoch, epochs):
        t0 = time.time()

        train_loss = run_epoch(
            model, train_loader, criterion, optimizer, scaler, device,
            train=True, grad_clip=grad_clip, accum_steps=accum_steps,
            mixed_precision=use_amp, amp_dtype=amp_dtype,
            skip_nonfinite_batches=skip_nonfinite_batches,
            oom_skip_batches=oom_skip_batches,
        )

        val_loss = run_epoch(
            model, val_loader, criterion, optimizer, scaler, device,
            train=False, grad_clip=grad_clip, accum_steps=accum_steps,
            mixed_precision=use_amp, amp_dtype=amp_dtype,
            skip_nonfinite_batches=skip_nonfinite_batches,
            oom_skip_batches=oom_skip_batches,
        )

        # Scheduler step
        if sched_mode == "epoch" and isinstance(
            scheduler, (torch.optim.lr_scheduler.LambdaLR, torch.optim.lr_scheduler.StepLR)
        ):
            scheduler.step()
        elif sched_mode == "plateau" and isinstance(
            scheduler, torch.optim.lr_scheduler.ReduceLROnPlateau
        ):
            scheduler.step(float(val_loss))

        current_lr = optimizer.param_groups[0]["lr"]

        # TensorBoard
        writer.add_scalar("Loss/Train",      train_loss, epoch)
        writer.add_scalar("Loss/Val",        val_loss,   epoch)
        writer.add_scalar("LR",              current_lr, epoch)

        # Save best
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            # Save raw state_dict (unwrap compiled model if needed)
            raw_model = cast(nn.Module, model._orig_mod) if hasattr(model, "_orig_mod") else model
            best_dir = os.path.dirname(best_path)
            if best_dir:
                os.makedirs(best_dir, exist_ok=True)
            torch.save(raw_model.state_dict(), best_path)
            print(f"  ✓ Best model saved  (val={best_val_loss:.6f})")

        # Checkpoint
        save_checkpoint(ckpt_save, epoch, model, optimizer, scheduler, scaler, best_val_loss)

        # Logging
        mem_used, mem_total, power = get_gpu_stats()
        elapsed = time.time() - t0
        print(f"Epoch {epoch+1:>3}/{epochs}  |  "
              f"Train {train_loss:.6f}  Val {val_loss:.6f}  |  "
              f"LR {current_lr:.2e}  |  {elapsed:.1f}s")
        if mem_used is not None:
            print(f"             GPU {mem_used}/{mem_total} MB  |  "
                  f"Power {power:.1f} W")

        # Flush VRAM fragment cache
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()

        # Early stopping
        if stopper is not None and stopper.step(val_loss):
            print(f"\n[EarlyStopping] No improvement for {stopper.patience} epochs — stopping.")
            break

        if _interrupted:
            print("[INFO] Exiting cleanly after user interrupt.")
            break

    writer.close()
    print("\n===== Training Complete 🚀 =====")
    print(f"Best val loss : {best_val_loss:.6f}")
    print(f"Best model    : {best_path}")
    print(f"TensorBoard   : tensorboard --logdir={log_dir}")


# =============================================================================
# ENTRY POINT
# =============================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="RAPTOR 6D Pose Training")
    parser.add_argument(
        "--config", type=str,
        default=str(Path(__file__).parent / "config.yaml"),
        help="Path to YAML config file (default: config.yaml next to this script)",
    )
    args = parser.parse_args()

    if not os.path.exists(args.config):
        print(f"[ERROR] Config file not found: {args.config}")
        sys.exit(1)

    main(args.config)
